repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: detect-private-key
    - id: mixed-line-ending
      args:
      - --fix=auto
    - id: pretty-format-json
      args:
      - --autofix
